### ISSUE TITLE
Todo App 요구사항 명세서 작성

### ISSUE THREAD

**Issue by mellomello-made** [mellomello-made/todo-app#1]
### 만들고자 하는 기능이 무엇인가?
Todo 생성 기능

### 해당 기능을 구현하기 위해 할 일이 무엇인가?
1. [ ] Text 입력창 생성
2. [ ] submit 버튼 클릭시 목록으로 생성
3. [ ] 삭제 버튼으로 제거 생성

### 예상 작업 시간
4h
